# DKDK Solr docker only

version: '3'

volumes:
    volume_solrdata_v1:         # Store solr cores' data and configs

services:
    solr:
        build:
            context: ./docker-solr/8.2
            dockerfile: Dockerfile_dk1
        volumes:
            - volume_solrdata_v1:/var/solr/
        ports:
            - "8080:8983"       #VEuPathDB: the port 8080 may need to be changed depending on Ash's port availability
